---
- name: Bastion server
  hosts: all
  roles:
    - "common"
    - "ansible"
    - role: td-agent
      when: enable_tdagent is undefined or enable_tdagent == '1'
  vars:
    tdagent_conf_template: templates/cassandra-server/td-agent.conf.j2
  gather_facts: no
  become: yes

- name: Set up multiple authorized keys
  hosts: all
  gather_facts: false
  tasks:
    - name: add key
      authorized_key:
        user: centos
        state: present
        key: "{% for key in lookup('fileglob', 'files/ssh_public/*.pub').split(',') %}{{ lookup('file', key) ~ '\n'}}{% endfor %}"
  tags:
  - ssh

